### PR TITLE
Chaning Twitter Blue Badge Color

### LINKED ISSUE #107: [Feature Request] A way to either hide or distinguish Twitter Blue checks from real ones
Similar to the extension EightDollars, it would be nice if there were a way to distinguish paid checks from real ones, or hide the paid ones altogether.
https://github.com/wseagar/eight-dollars

### PR DESCRIPTION
**Pull request by ExTBH**
Closes #107

### CODE REVIEW

**Comment by ExTBH** [comment]
could be replaced with a Color picker or another icon
https://github.com/BandarHL/BHTwitter/blob/f378082b499477298b04c0a8131ae9bd3698f3de/BHTwitter/BHTwitter.x#L719-L721

**Comment by ExTBH** [comment]
This hook is for timeline only, haven't wrote a threads hook

**Comment by BandarHL** [comment]
In profile view controller it just NSAttributedString with icon NSTextAttachment.
But you’re code in the timeline it make it laggy I believe there is a better way to do it

**Comment by ExTBH** [comment]
i don't notice performance loss with it enabled/disabled but i could dig deeper

**Comment by ExTBH** [comment]
@BandarHL can you try this? 1 hook for timeline and threads, reduced checks

**Pull request closed without merging**
